[project]
name = "travel-buddy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andreas SandstrÃ¶m", email = "66973334+Sandstrom96@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "lancedb>=0.27.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "pydantic-ai>=1.44.0",
    "streamlit>=1.53.0",
]

[project.scripts]
travel-buddy = "travel_buddy:main"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"
