[project]
name = "travel-buddy"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "google-generativeai",
    "pandas",
    "pydantic-ai",
    "streamlit>=1.40.0",
    "uvicorn",
    "lancedb",
    "setuptools>=80.10.2",
    "ipykernel>=7.1.0",
]
